title: CPT-Warmup
description: "August 2023 to June 2024"
owner_name: Imaad Muzaffer
github_username: Imaad08
github_repo: "tri-2-csp"
baseurl: "/csp-project"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/Djxnxnx" }
    - { platform: github, user_url: "https://github.com/Imaad08" }
    - { platform: github, user_url: "https://github.com/TejM123" }
    - { platform: github, user_url: "https://github.com/RonitT1234" }
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
future: true
